### ISSUE TITLE
Add 'force re-sync' or similar option

### ISSUE THREAD

**Issue by GWBid** [microsoft/advanced-formula-environment#20]
I've been doing a lot of copy/pasting from one workbook's AFE to another, and I've found it seems to be possible to break the synchronization, where the only solution is to delete everything and start from scratch.  When I'm trying to bring in 10+ namespaces, this can get quite annoying.

The specific error that happens is when I copy code that references a table that doesn't yet exist in the file I'm copying to.  This seems to break the synchronization process somehow, and even ensuring the table exists and is named properly doesn't seem to work.  It seems like certain functions get flagged as having been copied even if they haven't.  I've found that renaming a function, syncing, then renaming it back to what it's supposed to be, and re-syncing, works, but this is incredibly tedious when I have 50+ names that are affected.

I've tried this with both the hidden sheet enabled, and without, and it doesn't seem to make a difference.

If there was a way to just force it to resynchronize all names, I think this would solve the issue.

**Comment by jack-williams** [comment]
Thanks for the report @GWBid. You inference about the break is correct. The fundamental problem is that when synchronizing a collection of names using the Office API, if a particular name fails to sync (because it references an unknown table), we do not know which one.

When you combine this with the caching we do to avoid synchronizing unchanged names, this gets into bad states.

Marking this as a bug. I've started working on fixes to avoid caching in the event of a sync failure.

Out of interest, what mechanism are you using for bringing names across? Manual copy/paste?

**Comment by GWBid** [comment]
Thanks Jack, that's correct, I'm just doing manual copy/paste right now.  I tried some of the import/export functionality, but found that copy/pasting seemed to work better for my use.

Basically, I use Excel for engineering calculations, so I've built a library of lambdas that I re-use for various different applications.  When I make updates to the library functions, I'm looking for the easiest way to update other files based on this.
