### ISSUE TITLE
Named function creator doesn't work?

### ISSUE THREAD

**Issue by parched** [microsoft/advanced-formula-environment#25]
I've just tried the new named function creator. It looks great, but I can't get it to work.

It just puts `="="` in the name, instead of `=LAMBDA(...)`.

![image](https://user-images.githubusercontent.com/5975405/202531732-c0224446-1bd3-4e40-9cb2-89e5b90a6540.png)

**Comment by parched** [comment]
Ok, I've found the issue, I didn't put `=` at the start of the function definition. Perhaps, the `=` could be made optional as it seems redundant.

**Comment by jack-williams** [comment]
Yes, the function definition needs to start with `=`. We made this choice to be consistent with the built-in name manager. However, the name manager does not have a function editor, and it does not seem intended to create a function with a body that is not a formula.

I'll mark this as a bug because I do not think writing `="="` is the right behavior.

**Comment by jack-williams** [comment]
We've update AFE to address this issue. When creating a new name we automatically insert a leading `=` in the starting text. This should make it clearer that the formula needs to include `=`.

We considered making the `=` optional, but ended up preferring consistency with the existing name box.

![image](https://user-images.githubusercontent.com/4489219/205276521-7b62d85a-0da7-4c62-9054-9ab3e092612f.png)
