### ISSUE TITLE
External library ("Import from URL") [question]

### ISSUE THREAD

**Issue by ammosov** [microsoft/advanced-formula-environment#36]
This is a request for clarification or tutorial, not a bug report. 

what steps must be followed to create and load an external library from Github (or for that matter, locally)?

**Comment by ammosov** [comment]
Do I assume correctly that gist is a plain text file, and a module is copy-pasted to gist as plain text?  If yes, how it should be formatted (indents by space, indents by tab, etc) to be readable as an external library?

**Comment by jack-williams** [comment]
> Do I assume correctly that gist is a plain text file, and a module is copy-pasted to gist as plain text?

Yes. Either copy-paste or imported using a gist url. 

You'll need to be careful that the text does not contain carriage return characters `\r` or tabs `\t`, so indents needs to be spaces. (We'll likely change AFE to support this on paste, but it's not implemented yet).

> formatted (indents by space, indents by tab, wrapping/no wrap etc) to be readable as an external library

As above, the only requirement for it to work is no tabs. Otherwise, AFE can work with any indent level, wrapping or not.

In terms of what is readable to people, we currently have no requirements of layout. If we add a collection of libraries to AFE built-in that uses can contribute to, we'll make clear the style requirements.

**Comment by ammosov** [comment]
> You'll need to be careful that the text does not contain carriage return characters \r or tabs \t, so indents needs to be spaces. 

Does this mean that myFun = lambda(a, b, a+b) can only be pasted as a single line, or does it allow to paste as

`myFun = lambda(`
`....a, `
`....b, `
`....a+b`
`)`


as long as all indents are spaces only?

**Comment by jack-williams** [comment]
> as long as all indents are spaces only?

Yes, can be across multiple lines as long as indents are spaces only.

**Comment by ammosov** [comment]
With your permission, I close this.
